import { config } from "dotenv";
import { PrismaPg } from "@prisma/adapter-pg";
import { PrismaClient } from "../src/generated/prisma/client";

config({ path: ".env.local" });

const adapter = new PrismaPg({ connectionString: process.env.DATABASE_URL });
const prisma = new PrismaClient({ adapter });

const img = (n: number) => `/images/products/product-${String(n).padStart(2, "0")}.jpg`;

const products = [
  {
    slug: "pearl-bloom-huggie-earrings",
    name: "Pearl Bloom Huggie Earrings",
    category: "Earrings",
    price: 1800,
    image: img(1),
    description:
      "Matte gold-toned huggies wrapped around a lustrous faux pearl — an everyday piece that carries quietly into evening wear.",
    finish: "18K Gold Plated",
    collections: ["quiet-luxury-daily"],
    isNew: false,
  },
  {
    slug: "hammered-dome-stud-earrings",
    name: "Hammered Dome Stud Earrings",
    category: "Earrings",
    price: 1600,
    image: img(2),
    description:
      "Hand-hammered gold domes catch light from every angle — a sculptural stud built for daily rotation.",
    finish: "18K Gold Plated",
    collections: ["quiet-luxury-daily"],
    isNew: false,
  },
  {
    slug: "pearl-drop-gold-hoops",
    name: "Pearl Drop Gold Hoops",
    category: "Earrings",
    price: 2200,
    image: img(3),
    description:
      "Slim gold hoops suspending a single pearl drop — a bridge piece between minimal and statement.",
    finish: "18K Gold Plated",
    collections: ["quiet-luxury-daily", "desi-wedding-essentials"],
    isNew: false,
  },
  {
    slug: "ridged-gold-huggies",
    name: "Ridged Gold Huggies",
    category: "Earrings",
    price: 1700,
    image: img(4),
    description: "Deep ridged texture wraps this huggie hoop for a faceted, light-catching finish.",
    finish: "18K Gold Plated",
    collections: ["quiet-luxury-daily"],
    isNew: false,
  },
  {
    slug: "sunburst-drop-earrings",
    name: "Sunburst Drop Earrings",
    category: "Earrings",
    price: 2000,
    image: img(5),
    description: "An open sunburst silhouette in polished gold — light, sculptural, and unmistakably distinct.",
    finish: "18K Gold Plated",
    collections: ["desi-wedding-essentials"],
    isNew: true,
  },
  {
    slug: "antique-bloom-ring-set",
    name: "Antique Bloom Ring Set (4pc)",
    category: "Rings",
    price: 3500,
    image: img(6),
    description:
      "Four oxidised-silver floral rings with dense filigree detail, sold as a set for stacking or gifting.",
    finish: "Oxidised Silver Plated",
    collections: ["desi-wedding-essentials"],
    isNew: false,
  },
  {
    slug: "teal-charm-bookmark-necklace",
    name: "Teal Charm Bookmark Necklace",
    category: "Accessories",
    price: 2800,
    image: img(7),
    description:
      "A gold bookmark set with teal cabochon charms — for readers who want their jewellery box and bookshelf to match.",
    finish: "18K Gold Plated",
    collections: ["quiet-luxury-daily"],
    isNew: true,
  },
  {
    slug: "beaded-heart-pendant-necklace",
    name: "Beaded Heart Pendant Necklace",
    category: "Necklaces",
    price: 2400,
    image: img(8),
    description: "A row of polished gold beads leads to a soft heart pendant on a fine chain.",
    finish: "18K Gold Plated",
    collections: ["quiet-luxury-daily"],
    isNew: false,
  },
  {
    slug: "scalloped-shell-cuff-bangle-set",
    name: "Scalloped Shell Cuff & Bangle Set",
    category: "Bracelets",
    price: 4200,
    image: img(9),
    description:
      "Sculptural scalloped-shell cuffs paired with a stack of slim bangles — a full arm party in one set.",
    finish: "18K Gold Plated",
    collections: ["desi-wedding-essentials"],
    isNew: false,
  },
  {
    slug: "stone-cluster-statement-ring",
    name: "Stone Cluster Statement Ring",
    category: "Rings",
    price: 2600,
    image: img(10),
    description:
      "Oxidised silver settings cluster smoky and mother-of-pearl stones into an heirloom-style statement ring.",
    finish: "Oxidised Silver Plated",
    collections: ["desi-wedding-essentials"],
    isNew: false,
  },
  {
    slug: "colorblock-enamel-stud-earrings",
    name: "Colorblock Enamel Stud Earrings",
    category: "Earrings",
    price: 1500,
    image: img(11),
    description: "Geometric enamel blocks in forest green and cream, set in a slim gold frame.",
    finish: "Gold Plated / Enamel",
    collections: ["quiet-luxury-daily"],
    isNew: false,
  },
  {
    slug: "gilded-seashell-trinket-box",
    name: "Gilded Seashell Trinket Box",
    category: "Accessories",
    price: 3000,
    image: img(12),
    description:
      "A clamshell-shaped trinket box in polished gold — the resting place for the pieces you take off each night.",
    finish: "Gold Plated",
    collections: ["quiet-luxury-daily"],
    isNew: false,
  },
  {
    slug: "tortoise-shell-hoop-earrings",
    name: "Tortoise Shell Hoop Earrings",
    category: "Earrings",
    price: 1900,
    image: img(13),
    description: "Warm tortoise-shell acetate hoops with a gold post — a texture-forward everyday hoop.",
    finish: "Acetate / Gold Plated Post",
    collections: ["quiet-luxury-daily"],
    isNew: false,
  },
  {
    slug: "rose-motif-pendant-necklace",
    name: "Rose Motif Pendant Necklace",
    category: "Necklaces",
    price: 2700,
    image: img(14),
    description: "A hand-etched rose pendant on a fine gold snake chain — soft, romantic, and quietly detailed.",
    finish: "18K Gold Plated",
    collections: ["quiet-luxury-daily"],
    isNew: false,
  },
  {
    slug: "garnet-heart-pendant-necklace",
    name: "Garnet Heart Pendant Necklace",
    category: "Necklaces",
    price: 2500,
    image: img(15),
    description: "A deep garnet-toned heart set in gold, strung on a delicate textured chain.",
    finish: "18K Gold Plated",
    collections: ["desi-wedding-essentials"],
    isNew: false,
  },
  {
    slug: "noir-rose-pendant-necklace",
    name: "Noir Rose Pendant Necklace",
    category: "Necklaces",
    price: 2300,
    image: img(16),
    description: "A matte black oval pendant engraved with a gold rose — dark, minimal, and easy to layer.",
    finish: "Gold Plated / Enamel",
    collections: ["quiet-luxury-daily"],
    isNew: false,
  },
  {
    slug: "hammered-chain-link-ring",
    name: "Hammered Chain-Link Ring",
    category: "Rings",
    price: 1800,
    image: img(17),
    description: "A hammered-texture band built from interlocking chain-link circles.",
    finish: "18K Gold Plated",
    collections: ["quiet-luxury-daily"],
    isNew: false,
  },
  {
    slug: "crossover-twist-ring",
    name: "Crossover Twist Ring",
    category: "Rings",
    price: 1600,
    image: img(18),
    description: "A polished crossover band with a soft twisted silhouette — a quiet-luxury staple.",
    finish: "18K Gold Plated",
    collections: ["quiet-luxury-daily"],
    isNew: false,
  },
  {
    slug: "solitaire-cocktail-ring",
    name: "Solitaire Cocktail Ring",
    category: "Rings",
    price: 2900,
    image: img(19),
    description: "A round brilliant-cut solitaire held by a textured, scalloped gold band.",
    finish: "18K Gold Plated / CZ",
    collections: ["desi-wedding-essentials"],
    isNew: false,
  },
  {
    slug: "cherry-drop-earrings",
    name: "Cherry Drop Earrings",
    category: "Earrings",
    price: 1700,
    image: img(20),
    description: "Glossy resin cherries suspended from a fine gold bar post — playful and unmistakably fun.",
    finish: "Gold Plated / Resin",
    collections: ["quiet-luxury-daily"],
    isNew: true,
  },
  {
    slug: "mixed-gold-ring-stack",
    name: "Mixed Gold Ring Stack (6pc)",
    category: "Rings",
    price: 4800,
    image: img(21),
    description:
      "Six sculptural gold rings — domes, signets, and open bands — designed to be worn stacked or separate.",
    finish: "18K Gold Plated",
    collections: ["quiet-luxury-daily"],
    isNew: false,
  },
  {
    slug: "chrome-teardrop-earrings",
    name: "Chrome Teardrop Earrings",
    category: "Earrings",
    price: 2100,
    image: img(22),
    description: "Bold sculptural teardrops in a high-shine chrome and gold mix — a modern statement piece.",
    finish: "Gold & Rhodium Plated",
    collections: ["quiet-luxury-daily"],
    isNew: true,
  },
  {
    slug: "panther-link-bracelet",
    name: "Panther Link Bracelet",
    category: "Bracelets",
    price: 3400,
    image: img(23),
    description: "A dense panther-link chain bracelet with a fold-over clasp — substantial and everyday-durable.",
    finish: "18K Gold Plated",
    collections: ["quiet-luxury-daily"],
    isNew: false,
  },
  {
    slug: "four-leaf-clover-necklace",
    name: "Four Leaf Clover Necklace",
    category: "Necklaces",
    price: 2200,
    image: img(24),
    description: "A finely etched four-leaf clover pendant on a snake chain — a rare-find charm for good luck.",
    finish: "18K Gold Plated",
    collections: ["quiet-luxury-daily"],
    isNew: false,
  },
  {
    slug: "pearl-heart-charm-necklace",
    name: "Pearl & Heart Charm Necklace",
    category: "Necklaces",
    price: 2600,
    image: img(25),
    description: "A double-layered chain scattered with freshwater pearls and mother-of-pearl heart charms.",
    finish: "18K Gold Plated / Freshwater Pearl",
    collections: ["quiet-luxury-daily", "desi-wedding-essentials"],
    isNew: false,
  },
  {
    slug: "cinderella-charm-bracelet",
    name: "Cinderella Charm Bracelet",
    category: "Bracelets",
    price: 2400,
    image: img(26),
    description: "Blue and teal cabochon stones set in silver-tone links — an ode to a favourite fairytale.",
    finish: "Rhodium Plated",
    collections: ["desi-wedding-essentials"],
    isNew: false,
  },
  {
    slug: "repunzel-charm-bracelet",
    name: "Repunzel Charm Bracelet",
    category: "Bracelets",
    price: 2400,
    image: img(27),
    description: "Blush and rose-toned stones set in silver-tone links — soft, storybook charm for the wrist.",
    finish: "Rhodium Plated",
    collections: ["desi-wedding-essentials"],
    isNew: false,
  },
];

async function main() {
  for (const product of products) {
    await prisma.product.upsert({
      where: { slug: product.slug },
      update: product,
      create: product,
    });
  }
  console.log(`Seeded ${products.length} products.`);
}

main()
  .catch((e) => {
    console.error(e);
    process.exitCode = 1;
  })
  .finally(async () => {
    await prisma.$disconnect();
  });
